// Define all unique markets once
const m = {
  '1x2': { code: '1x2', ns: '1,X,2', priceCount: 3 },
  DC: { code: 'DC', ns: '1X,12,X2', priceCount: 3 },
  BTS: { code: 'BTS', ns: 'Yes,No', priceCount: 2, name: 'BTS' },
  AH: {
    code: 'AH',
    ns: '1,2',
    priceCount: 2,
    withHandicap: true,
    name: 'Asian Handicap',
  },
  OU: {
    code: 'OU',
    ns: 'Over,Under',
    priceCount: 2,
    withHandicap: true,
    name: 'Handicap',
  },
  HA: { code: 'HA', ns: '1,2', priceCount: 2 },
  HA_OT: { code: 'HA_OT', ns: '1,2', priceCount: 2 },
  OT: { code: 'OT', ns: 'Yes,No', priceCount: 2 },
  AH_OT: { code: 'AH_OT', ns: '1,2', priceCount: 2, withHandicap: true },
  OU_OT: { code: 'OU_OT', ns: 'Over,Under', priceCount: 2, withHandicap: true },
  OU_HCO: {
    code: 'OU_HCO',
    ns: '+,-',
    priceCount: 2,
    name: 'Highest Checkout Score 2-Way',
  },
  OU_G: {
    code: 'OU_G',
    ns: '+,-',
    priceCount: 2,
    name: 'Over/Under by Games in Match',
  },
  AH_S: { code: 'AH_S', ns: '1,2', priceCount: 2, withHandicap: true },
  OU_S: { code: 'OU_S', ns: '+,-', priceCount: 2, withHandicap: true },
  AH_G: { code: 'AH_G', ns: '1,2', priceCount: 2 },
  HA_S1: { code: 'HA_S1', ns: '1,2', priceCount: 2 },
  HA_S2: { code: 'HA_S2', ns: '1,2', priceCount: 2 },
  TB: { code: 'TB', ns: 'Yes,No', priceCount: 2 },
  '1x2_I1': { code: '1x2_I1', ns: '1,X,2', priceCount: 3 },
  AH_I1: {
    code: 'AH_I1',
    ns: '1,2',
    priceCount: 2,
    withHandicap: true,
    name: 'Asian Handicap (1st Inning)',
  },
  AH_H1: {
    code: 'AH_H1',
    ns: '1,2',
    priceCount: 2,
    withHandicap: true,
    name: 'Asian Handicap (1st Half)',
  },
  HA_K: { code: 'HA_K', ns: '1,2', priceCount: 2, name: 'Home/Away Kills' },
  DNB: {
    code: 'DNB',
    ns: '1,2',
    name: 'Draw No Bet',
    priceCount: 2,
  },
};

// Use references in the mapper
export const marketsMapper = {
  50: [m['1x2'], m['DC'], m['BTS'], m['AH'], m['OU']],
  51: [m['1x2'], m['DC'], m['AH'], m['OU'], m['BTS']],
  52: [m['HA'], m['HA_S1'], m['HA_S2'], m['TB']],
  53: [m['HA_OT'], m['OT'], m['AH_OT'], m['OU_OT']],
  54: [m['HA'], m['AH_S'], m['OU_S'], m['AH_G']],
  55: [m['1x2'], m['DC'], m['OU'], m['AH']],
  56: [m['HA_OT'], m['1x2_I1'], m['AH_I1']],
  57: [m['HA'], m['AH'], m['OU']],
  58: [m['1x2'], m['AH'], m['OU']],
  59: [m['HA'], m['AH_G'], m['AH_S'], m['OU_S']],
  60: [m['1x2'], m['DC'], m['AH']],
  61: [m['HA'], m['AH'], m['OU']],
  62: [m['HA'], m['AH'], m['OU']],
  63: [m['HA_OT'], m['1x2'], m['AH_OT'], m['OU']],
  64: [m['1x2'], m['AH'], m['OU']],
  65: [m['1x2'], m['AH'], m['OU']],
  66: [m['1x2'], m['HA'], m['AH'], m['DC']],
  67: [m['AH_H1']],
  69: [m['HA'], m['AH'], m['OU'], m['OU_HCO']],
  70: [m['HA'], m['AH_S'], m['OU_S'], m['AH']],
  71: [m['AH'], m['HA']],
  72: [m['HA'], m['HA'], m['OE'], m['OU']],
  73: [m['HA']],
  75: [m['1x2'], m['HA'], m['DC'], m['OU']],
  78: [m['HA'], m['AH_G'], m['OU_S']],
  82: [m['1x2']],
  90: [m['HA']],
  92: [m['HA'], m['AH'], m['OU']],
  93: [m['OU'], m['AH'], m['AH_S']],
  94: [m['1x2']],
  95: [m['HA'], m['AH'], m['HA_K']],
  96: [m['HA']],
  99: [m['1x2'], m['AH'], m['DC'], m['DNB']],
  100: [m['HA'], m['1x2']],
  101: [m['AH'], m['OU']],
  107: [m['1x2'], m['DC'], m['BTS'], m['AH'], m['OU']],
  108: [m['HA_OT'], m['OT'], m['AH_OT'], m['OU_OT']],
  110: [m['1x2'], m['DC'], m['AH'], m['OU'], m['BTS']],
  116: [m['1x2'], m['AH'], m['OU']],
  128: [m['1x2'], m['AH'], m['OU']],
  129: [m['AH']],
  130: [m['1x2'], m['AH'], m['OU_G']],
  134: [m['HA']],
  140: [m['HA'], m['HA_S1']],
  143: [m['HA']],
  145: [m['HA'], m['OU']],
  148: [m['HA']],
  150: [m['HA']],
};
